create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'admin' check (role = 'admin'),
  endpoint text unique not null,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.push_subscriptions enable row level security;

revoke all on table public.push_subscriptions from anon;
grant select, insert, update, delete on table public.push_subscriptions to authenticated;
grant usage, select on sequence public.push_subscriptions_id_seq to authenticated;

create or replace function public.set_push_subscriptions_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_push_subscriptions_updated_at on public.push_subscriptions;
create trigger set_push_subscriptions_updated_at
before update on public.push_subscriptions
for each row execute function public.set_push_subscriptions_updated_at();

drop policy if exists "Admins can read own push subscriptions" on public.push_subscriptions;
create policy "Admins can read own push subscriptions"
on public.push_subscriptions for select
to authenticated
using ((select auth.uid()) = user_id and role = 'admin');

drop policy if exists "Admins can insert own push subscriptions" on public.push_subscriptions;
create policy "Admins can insert own push subscriptions"
on public.push_subscriptions for insert
to authenticated
with check ((select auth.uid()) = user_id and role = 'admin');

drop policy if exists "Admins can update own push subscriptions" on public.push_subscriptions;
create policy "Admins can update own push subscriptions"
on public.push_subscriptions for update
to authenticated
using ((select auth.uid()) = user_id and role = 'admin')
with check ((select auth.uid()) = user_id and role = 'admin');

drop policy if exists "Admins can delete own push subscriptions" on public.push_subscriptions;
create policy "Admins can delete own push subscriptions"
on public.push_subscriptions for delete
to authenticated
using ((select auth.uid()) = user_id and role = 'admin');
