create table public.schedule_blocks (
  id bigint generated by default as identity primary key,
  block_date date not null,
  start_time time,
  end_time time,
  all_day boolean not null default false,
  reason text,
  created_at timestamptz not null default now(),
  constraint schedule_blocks_time_check check (
    (
      all_day = true
      and start_time is null
      and end_time is null
    )
    or
    (
      all_day = false
      and start_time is not null
      and end_time is not null
      and end_time > start_time
    )
  )
);

alter table public.schedule_blocks enable row level security;

revoke all on table public.schedule_blocks from anon, authenticated;
grant select (block_date, start_time, end_time, all_day) on table public.schedule_blocks to anon;
grant select on table public.schedule_blocks to authenticated;
grant insert, delete on table public.schedule_blocks to authenticated;
grant usage, select on sequence public.schedule_blocks_id_seq to authenticated;

create policy "schedule_blocks_public_select"
on public.schedule_blocks
for select
to anon
using (true);

create policy "schedule_blocks_authenticated_select"
on public.schedule_blocks
for select
to authenticated
using (true);

create policy "schedule_blocks_authenticated_insert"
on public.schedule_blocks
for insert
to authenticated
with check (true);

create policy "schedule_blocks_authenticated_delete"
on public.schedule_blocks
for delete
to authenticated
using (true);

alter publication supabase_realtime add table public.schedule_blocks;
